e_shop/cart/urls.py
from django.urls import path
from cart import views


app_name = 'cart'


urlpatterns = [
    path('', views.cart_page, name = 'cart'),
    path('add_item/', views.add_item, name = 'add'),
]

e_shop/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from core import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace = 'main')),
    path('catalog/', include('goods.urls', namespace = 'catalog')),
    path('profile/', include('users.urls', namespace = 'profile')),
    path('cart/', include('cart.urls', namespace='cart'))
]

# debug on only
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

e_shop/goods/urls.py
from django.urls import path

from goods import views


app_name = 'goods'

urlpatterns = [
    path('', views.catalog, name = 'index'),
    path('search/', views.catalog, name = 'search'),
    path('product/<str:search_slug>/', views.product_page, name = 'product')
]

e_shop/main/urls.py
from django.urls import path

from main import views


app_name = 'main'

urlpatterns = [
    path('', views.home, name = 'home')
]

e_shop/users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_page, name = 'login'),
    path('logout/', views.logout_page, name = 'logout'),
    path('registration/', views.registration, name = 'register'),
    path('profile_page/', views.profile, name = 'user_page'),
]

e_shop/cart/models.py
from django.db import models
from goods.models import Products
from django.contrib.auth.models import User

class Order(models.Model):
    buyer = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    operation_id = models.CharField(max_length=100)

class Order_element(models.Model):
    item = models.ForeignKey(Products,on_delete= models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete= models.SET_NULL, null = True)
    count = models.IntegerField(default=0, null = True)
    add_date = models.DateTimeField(auto_now_add=True)

e_shop/goods/models.py
from django.db import models

class Products(models.Model):
    class Meta:
        db_table = 'products'

    name = models.CharField(max_length = 100, null = False)
    color = models.CharField(max_length = 30)
    price = models.FloatField(max_length = 100000, null = False)
    description = models.CharField(max_length=5000)
    image = models.ImageField(upload_to='goods_images')
    slug = models.SlugField(default = "", null = False)
    count = models.IntegerField(default=0)
    

e_shop/users/models.py
from django.db import models

e_shop/users/forms.py
from django import forms

class LoginForm(forms.Form):
    login = forms.CharField(max_length=100, label='Почта', widget=forms.EmailInput())
    password = forms.CharField(max_length=100, label='Пароль', widget=forms.PasswordInput())

e_shop/cart/views.py
from django.shortcuts import render
from django.http import JsonResponse
from goods.models import *
from .models import *
import json


# Create your views here.
def cart_page(request):
    return render(request, 'cart/cart.html')

def add_item(request):
    data = json.loads(request.body)
    product_id = data['product_id']
    action = data['action']
    print(action, product_id)


    return JsonResponse('Товар добавлен в корзину', safe=False)

e_shop/goods/views.py
from django.shortcuts import render
from goods.models import Products
from goods.utils import query_search

def catalog(request):
    query = request.GET.get('q', None)
    if query:
        goods = query_search(query)
    else:
        goods = Products.objects.all()

    return render(request, 'goods/catalog.html', {
        'title': 'Каталог',
        'goods': goods,
        'query': query,
        'count': len(goods)
    })


def product_page(request, search_slug):
    product = Products.objects.get(slug=search_slug)

    return render(request, 'goods/product_page.html',{
        'product': product
    })

e_shop/main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html', 
        {'title': 'Главная'})

e_shop/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from users.forms import LoginForm

def login_page(request):
    # error_msg = ''
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(request, username=data['login'], password=data['password'])

            if user and user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('main:home'))
            
        # if not form.is_valid():
        #     error_msg = 'Введеный пользователь не существует.'
        
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {
        'title': 'Вход',
        'form': form,
        # 'error_msg': error_msg 
    })

def registration(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            data = form.cleaned_data
            user = authenticate(request, username=data['username'], password=data['password2'])

            if user and user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('main:home'))

    else:
        form = UserCreationForm()
    return render(request, 'users/register.html', {'form': form})


def logout_page(request):
    logout(request)
    return HttpResponseRedirect(reverse('profile:login'))

def profile(request):
    return render(request, 'users/profile.html', {
        'title': 'Ваш профиль'
    })

e_shop/cart/templates/cart.html
{% extends "base.html" %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href='{% static "cart.css" %}'>
{% endblock %}

e_shop/cart/templates/cart/cart.html
{% extends "base.html" %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href='{% static "css/cart.css" %}'>
{% endblock %}

{% block content %}
    <p class = 'head'>Корзина</p>
    <div class="row">
		<div class="col-lg-12">
			<div class="box-element">
				<a class="btn btn-outline-dark" href="{% url 'catalog:index' %}">&#x2190; Вернуться к каталогу</a>
				<table class="table">
					<tr>
						<th><h4>Товаров: <strong></strong></h4></th>
						<th><h4>На сумму:<strong></strong></h4></th>
						<th>
                    </tr>
                </table>
{% endblock %}

e_shop/goods/templates/goods/catalog.html
{% extends "base.html" %} 
{% load static %}

{% block links %}
  <link rel="stylesheet" href="{% static 'css/catalog.css' %}">
  <script src="{% static 'js/cart.js' %}"></script>
  <script>
    function getCookie(name) {
      let cookieValue = null;
      if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
              const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
            }
        }
    }
    return cookieValue;
}
    const csrftoken = getCookie('csrftoken');
  </script>
{% endblock links %}

{% block title %}
  <title>{{ title }}</title>
{% endblock %}

{% block content %}
<h1 class = 'head'>Каталог</h1>

{% if query %}
  <h1 class = 'query'>Результаты по запросу '{{query}}': {{count}}</h2>
{% endif %}
<div class="catalog">
    {% for product in goods %}
    <div class="cards">
      {% if product.image %}
        <a href="{% url 'catalog:product' product.slug %}"> <img src="{{product.image.url}}" alt="{{ product.name }}" class="cards_img"> </a>
        {% else %}
        <img src="{% static 'img/image_not_found.jpeg' %}" alt="{{ product.name }}" class="cards_img">
      {% endif %}
      <div class="cards_title"><a href="{% url 'catalog:product' product.slug %}">{{ product.name }}</a></div>
      <div class="cards_price">{{ product.price }} ₽</div>
      <div class="btns_keeper">
        {% if user.is_authenticated %}
          <button class="btn btn-light cart-update" data-product="{{product.id}}" data-action = "add">В корзину</button>
        {% else %}
        <a href="{% url 'profile:register' %}" class="btn btn-light">В корзину</a>
        {% endif %}
      </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

e_shop/goods/templates/goods/product_page.html
{% extends "base.html" %} 
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static 'css/product_page.css' %}">
{% endblock %}

{% block content %}

<div class = 'wrap'>
    <img src="{{product.image.url}}" alt="" class = 'image'>
    <div class="params">
      <p class = 'name'>{{product.name}}</p>
      <p class = 'desc'>{{product.description}}</p>
      <p class = 'color'>{{product.color}}</p>
      <p class = 'price'>{{product.price}} ₽</p>
      {% if user.is_authenticated %}
          <button class="btn btn-light cart-update" data-product="{{product.id}}" data-action = "add">В корзину</button>
        {% else %}
        <a href="{% url 'profile:register' %}" class="btn btn-light">В корзину</a>
        {% endif %}
    </div>
</div>

{% endblock %}

e_shop/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block links %}
    {% endblock %}
    <title>Название</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
      <a class="navbar-brand" href="#">logo</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                  <a class="nav-link" href="#">Каталог</a>
              </li>
          </ul>

          <form class="d-flex" role="search">
              <input class="form-control me-2 custom" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
          </form>

          <div class="d-flex ms-auto">
              <a class="nav-link fw-light" href="#">
                  <i class="fa-solid fa-user --fa-font-solid"></i> Войти
              </a>
          </div>
      </div>
  </div>
</nav>
      {% block content %} {% endblock %}
</body>
</html>

e_shop/main/templates/main/home.html
{% extends "base.html" %}
{% load static %}

{% block links %}
  <link rel="stylesheet" href="{% static 'css/home.css' %}">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
{% endblock %}

{% block title %}
  <title>{{title}}</title>
{% endblock %}

{% block content %}
<h1 class="head">Купить хозтовары недорого в Ставрополе</h1>


<div class="main_section">
  <h1>Почему именно мы:</h1>
    <ul>
      <li>Низкие цены</li>
      <li>Высокое качество</li>
      <li>Быстрая доставка по всему городу</li>
    </ul>
</div>

{% endblock %}

e_shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block links %}
    {% endblock %}
    
    <!-- стили для навбара  -->
    <link rel="stylesheet" href="../../../static/css/base.css">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
    
    {% block title %}
    {% endblock %}

</head>
<body>

  <nav class="navbar navbar-expand-lg" style = "background-color:#FFF4D6;">
  <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'main:home'%}">logo</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'catalog:index' %}">Каталог</a>
              </li>
          </ul>

          <form class="d-flex" role="search" action = "{% url 'catalog:search' %}" method = "get">
              <input class="form-control me-2 custom" type="search" name = "q" required pattern="\S(.*\S)?" placeholder="Поиск" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Искать</button>
          </form>
          {% if user.is_authenticated %}
          <div class="d-flex ms-auto">
              <a class="nav-link fw-light" href="{% url 'cart:cart' %}">
                  <i class="fa-solid fa-cart-shopping"></i>Корзина
              </a>
          </div>

          <div>
            <div class="d-flex ms-auto">
                <a class="nav-link fw-light" href="{% url 'profile:user_page' %}">
                    <i class="fa-solid fa-user --fa-font-solid"></i>Профиль
                </a>
            </div>
          </div>
          {% else %}
          <div class="d-flex ms-auto">
            <a class="nav-link fw-light" href="{% url 'profile:login' %}">
                <i class="fa-solid fa-user --fa-font-solid"></i> Войти
            </a>
        </div>
          {% endif %}
      </div>
  </div>
</nav>
      {% block content %} {% endblock %}
</body>
</html>

e_shop/users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block links %}
  <link rel="stylesheet" href="{% static 'css/login.css' %}">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
{% endblock %}

{% block title %}
  <title>{{title}}</title>
{% endblock %}

{% block content %}
<h1 class = 'head'>Войти в аккаунт</h1>

<form action="" method="post" class="form">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Войти</button>
</form>

{% if error_msg != '' %}
  <p style="text-align: center; color: #ff0000;">{{ error_msg }}</p>
{% endif %}

{% endblock %}

e_shop/users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <p>Профиль</p>
    <a href="{% url 'profile:logout' %}">Выйти из аккаунта</a>
{% endblock %}

e_shop/users/templates/users/register.html
{% extends "base.html" %}
{% load static %}

{% block links %}
  <link rel="stylesheet" href="{% static 'css/register.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
{% endblock %}

{% block title %}
  <title>{{title}}</title>
{% endblock %}

{% block content %}
<h1 class = 'head'>Регистрация</h1>

<form action="" method="post" class="form">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" id = 'submit_button'>Создать аккаунт</button>
</form>

{% comment %} {% if error_msg != '' %}
  <p style="text-align: center; color: #ff0000;">{{ error_msg }}</p>
{% endif %} {% endcomment %}

{% endblock %}